### ISSUE TITLE
Zentraler Abruf für Kontaktverfolgung - Verbesserungen

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-rsvp#102]
tools.php?page=rrze-rsvp-tracking

- do_action('rrze-rsvp-checked-in', get_current_blog_id(), $bookingId); in bookingReplyCustomer() reicht nicht, da im Admin Booking-Status editiert werden kann
- Redundanz beseitigen in admin_page_tracking -> Tracking::getUsersInRoomAtDate()
- Search date [YYYY-MM-DD] : Date-picker CMB2 statt Text-Eingabefeld mit gefordertem YYYY-MM-DD Format
- $searchdate = filter_input(INPUT_GET, 'searchdate', FILTER_SANITIZE_STRING); // filter stimmt nicht
- Datenkonsistenz! eventuell UNIQUE KEY nutzen (uk_guest_room_time (start,end,room_post_id,hash_seat_name,hash_guest_firstname,hash_guest_lastname,hash_guest_email,hash_guest_phone)

**Comment by thenickless** [comment]
- Schedule -> deleteOldTrackingData()

**Comment by thenickless** [comment]
- Spaltenüberschriften im CSV

**Comment by thenickless** [comment]
- RECHTE!!! aktuell ist 'manage_options' eingestellt

**Comment by thenickless** [comment]
- Menü / Formular / ajax ... aus Class Tools in Class Tracking portieren plus Multisite/Singlesite Menü-Generierung beachten

**Comment by thenickless** [comment]
- Menü bei MultiSite zeigt Hinweis in der Art "Bitte wenden Sie sich an den Superadmin" (Text -> neues Feld in config textarea -> "general" )

**Comment by xwolfde** [comment]
Nicht das Menu, sondern der Inhalt der Seite, wo jetzt das Formular ist.

**Comment by thenickless** [comment]
Menüpunkt zeigt auf Hinweis ... :-D

**Comment by thenickless** [comment]
Notiz

2DO: 

In 

'contact_tracking_note' => 'Contact your SuperAdmin <a href="mailto:' . $sender_email . '>' . $sender_name . '</a> to receive contact tracking informations.',

werden derzeit wg sanitize_textarea_field die Tags entfernt (auch ohne sanitize_callback) 

=> https://codex.wordpress.org/Function_Reference/wp_kses 

nutzen.

**Comment by thenickless** [comment]
- Search date [YYYY-MM-DD] : Date-picker CMB2 statt Text-Eingabefeld mit gefordertem YYYY-MM-DD Format

=> CMB2 wäre an dieser Stelle nicht sinnvoll, da es Metaboxes erstellt & ein workaround, um lediglich die Datepicker-Funktionalität zu erhalten, für das Kontaktverfolgungsformular mMn ein Overkill wäre, daher schlicht als HTML5 Pattern + placeholder in https://github.com/RRZE-Webteam/rrze-rsvp/commit/d938f812e4aae271cca17bc11e6b0e541f76cfc8 umgesetzt:

'<input type="text" id="searchdate" name="searchdate" placeholder="YYYY-MM-DD" pattern="(?:19|20)[0-9]{2}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1[0-9]|2[0-9])|(?:(?!02)(?:0[1-9]|1[0-2])-(?:30))|(?:(?:0[13578]|1[02])-31))" value="' . $searchdate . '">'

**Comment by thenickless** [comment]
- Menü / Formular / ajax ... aus Class Tools in Class Tracking portieren plus Multisite/Singlesite Menü-Generierung beachten

umgesetzt in https://github.com/RRZE-Webteam/rrze-rsvp/commit/531038ce16045556810d2bd6f8681d8b0d478bfc

Unklar ist im Moment noch, wie der Menüpunkt in /wp-admin/network/index.php dann erstellt werden kann, wenn das Plugin NICHT netzwerkweit aktiviert ist.

**Comment by xwolfde** [comment]
Zur Not halt ein eigenes Netzwerkplugin.

**Comment by thenickless** [comment]
https://github.com/RRZE-Webteam/rrze-rsvp-network

**Comment by thenickless** [comment]
"Normalzustand: Die Funktion wird für den Admin unter Tools gezeigt.
Wenn aber ein Netzwerkplugin RRZE-RSVP-Network vorhanden ist, wird die Funktion stattdessen nur in den Netzwerkadmin-Tools gezeigt und bei der vorherigen Stelle gibt es nur ein Hinweis darauf."


Umsetzt in neuem Plugin rrze-rsvp-network https://github.com/RRZE-Webteam/rrze-rsvp-network + rrze-rsvp Stand https://github.com/RRZE-Webteam/rrze-rsvp/commit/ee04df246b25c0dd31d988a03eafdcf42f5925ef 


Gründe:
- Es gibt keine technische Möglichkeit, dass ein Plugin Menüs anlegt, wenn es nicht aktiviert wurde und ein Nicht-SuperAdmin hat auf einer Multisite auch keine WP-Rechte, um das Netzwerk-Dashboard zu verändern. rrze-rsvp hatte vor https://github.com/RRZE-Webteam/rrze-rsvp/commit/ee04df246b25c0dd31d988a03eafdcf42f5925ef nur dann ein Netzwerk-Menü anlegen können, wenn das Plugin netzwerkweit aktiviert wurde. Es ist aber notwendig, dass der Zentrale Abruf für Kontaktverfolgung auch dann auf einer Multisite möglich ist, wenn RRZE-RSVP nicht netzwerkweit aktiv ist. 

Umgesetzt in https://github.com/RRZE-Webteam/rrze-rsvp/commit/ee04df246b25c0dd31d988a03eafdcf42f5925ef und dem neuen Plugin RRZE-RSVP-Network https://github.com/RRZE-Webteam/rrze-rsvp-network 

Zusammenfassung:
- RRZE-RSVP-Network prüft, ob RRZE-RSVP existiert.
- RRZE-RSVP-Network erweitert lediglich die Klasse Tracking von RRZE-RSVP; Code-Updates erfolgen auf RRZE-RSVP
- Der Menüpunkt "Kontaktverfolgung" erscheint bei Singlesite und den Websites einer Multisite-Installation unter "Werkzeuge" bzw "Tools" 
- Auf einer Multisite erhält der Admin beim Aufruf die Info "Contact your SuperAdmin ... to receive  contact tracking informations.", die in den Einstellungen editierbar ist.
- Bei einer Multisite gibt es im Netzwerk-Dashboard einen eigenen Menüpunkt - siehe Screenshot
- Bei einer Multisite können nur SuperAdmin das CSV generieren. (Das können Admins auch nicht mit direktem URL-Aufruf umgehen)

![Bildschirmfoto 2020-08-31 um 17 23 38](https://user-images.githubusercontent.com/54806119/91737475-6be20480-ebaf-11ea-87ad-5f197b5c7ddb.png)

**Comment by thenickless** [comment]
Der Übersicht halber schließe ich das Issue - Grundfunktionalität ist umgesetzt - noch offene Punkte sind hier:

- https://github.com/RRZE-Webteam/rrze-rsvp/issues/110
- https://github.com/RRZE-Webteam/rrze-rsvp/issues/111
- https://github.com/RRZE-Webteam/rrze-rsvp/issues/112
