### ISSUE TITLE
Automatische Löschung der Buchungsbelegung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#11]
Daten der Platzbelegung bleiben entspr. der Corona-Verordnungen nur 4 Wochen nach dem Zeitpunkt der Platzbuchung erhalten und werden danach automatisch gelöscht.

Der Raumverantwortliche kann sie aber zuvor auch manuell löschen. (z.B. auf Anfrage eines Person, die eine sofortige Löschung möchte).

**Comment by rvdforst** [comment]
Ist erledigt.
