### ISSUE TITLE
Zentraler Abruf für Kontaktverfolgung (Zusammenwirken rrze-rsvp-network + rrze-rsvp)

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-rsvp#110]
Wie bisher umgesetzt [1]

aber 

rrze-rsvp muss noch prüfen, ob rrze-rsvp-network aktiv ist für:

- [x]  use case A "Multisite:  ohne rrze-rsvp-network":

- Admin darf CSV erstellen
=> Tracking-Tabelle PRO WEBSITE (nicht als zentrale Tracking-Tabelle wie in [1] umgesetzt)
=> danach Funktionalität wie in [1] für Singlesite umgesetzt

- [x]  use case B "Multisite:  rrze-rsvp-network wird NACH rrze-rsvp aktiviert":
- Admins dürfen CSV NICHT MEHR erstellen
- SuperAdmin erstellt CSV über Menüpunkt in Network-Dashboard
=> Merge aller lokalen Tracking-Tabellen in zentrale Tracking-Tabelle 
=> lokale Tracking-Tabellen werden gelöscht 
=> danach Funktionalität wie in [1] umgesetzt

- [x]  use case C "Multisite:  mit rrze-rsvp-network":
- Admin darf CSV NICHT erstellen
- SuperAdmin erstellt CSV über Menüpunkt in Network-Dashboard
=> ist umgesetzt in [1]

- [x]  use case D "Multisite:   rrze-rsvp-network wird DEAKTIVIERT":
- Admin darf CSV (wieder) erstellen
=> Lokale Tracking-Tabelle wird erstellt und mit den Daten von zentraler Tracking-Tabelle gefüllt, die zu dieser Website gehören 
=> Zentrale Tracking-Tabelle wird gelöscht
=> danach Funktionalität wie in [1] für Singlesite umgesetzt

- [x]  use cases E "Singlesite":
(Nutzung von rrze-rsvp-network ist unsinnig und somit auch die entsprechenden use cases.)
=> ist umgesetzt in [1]
=> falls auf einer Singlesite zusätzlich das rrze-rsvp-network installiert wird, geschieht nichts. (Grund: auf einer Singlesite existiert der Action-Hook "network_admin_menu" nicht.)

[1] Stand: https://github.com/RRZE-Webteam/rrze-rsvp/commit/e48783e48cfeb1ae5f32fb7e512394cb0f5ccffe#diff-bb2b21ef7774df8687ff02b0284505c6 und https://github.com/RRZE-Webteam/rrze-rsvp-network/commit/fce28fa8362ba643455a408efb5082824014ffb3

**Comment by thenickless** [comment]
Notiz für mich:

- Konstellationen durchtesten!
- exeption handling -> rrze-log hooks nutzen  
- mit 2DOs in Kommentar zu onLoaded geht's weiter

**Comment by rvdforst** [comment]
Es sollte unabhängig von der Art der WP-Installation nur eine Tracking-Tabelle geben. KEINE Tracking-Tabelle PRO WEBSITE! Der Index zur Unterscheidung der Datensätze (bspw. für SQL-Queries) ist die Website-ID.

**Comment by thenickless** [comment]
Entsprechend https://github.com/RRZE-Webteam/rrze-rsvp/issues/110#issuecomment-686344673 onLoaded() wesentlich vereinfacht in https://github.com/RRZE-Webteam/rrze-rsvp/commit/0751268f029050b200485f0f62fea0966cef4bc9

**Comment by thenickless** [comment]
wird über transition_post_status als do_action('rrze-rsvp-checked-in', get_current_blog_id(), $bookingId) immer aufgerufen, im Tracking wird geprüft, ob insert oder update (key = blogID + bookingID) 

done in https://github.com/RRZE-Webteam/rrze-rsvp/commit/c8437a37b394b06715b174701fb9bc4f6207b401
