### ISSUE TITLE
Probleme mit Beiträgen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#113]
Problemmeldung:

> Wenn das Plugin aktiv ist, entsteht ein Problem mit Beitragsseiten: Die Beiträge werden auf der Beitragsseite nur in der Kurzform angezeigt (wie in einem Blogroll), aber nicht in der sonst üblichen Langform.

Das Plugin wird auf einer dezentralen CMS Installation betrieben

**Comment by thenickless** [comment]
Auf meinem Server ist das mit Theme "FAU-Einrichtungen" auch so: Beiträge nur als Exzerpt / in Kurzform. 
Aber die Beiträge werden korrekt in Langform angezeigt, wenn das Theme "Twenty Twenty", "Twenty Nineteen" oder "Twenty Seventeen" verwendet wird.

**Comment by rvdforst** [comment]
Der Fehler wurde behoben. Vgl. ee2ce115f10d97e7701bb1c42f95ff82ab84b814
