### ISSUE TITLE
Anzeigefehler Zeitslot: Bei Kalenderauswahl

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#119]
Der Fehler ist auch noch bei der Kalenderauswahl:
![grafik](https://user-images.githubusercontent.com/1070669/91996806-ef733100-ed28-11ea-8444-a9fe8b4bbef9.png)

Bei dem anderen Fall, wo es schonmal war, lag es an der führenden Null bei der Ausgabe der Stunde beim date-Format. Damit wurde der Indexeintrag uim Array nicht gefunden, da dort keine führende Null ist.

**Comment by rvdforst** [comment]
Dies entspricht einem Fehler im Zeitformat, der bereits behoben wurde. Da der Wert mit dem falschen Format in der DB gespeichert wurde, müssen die Metadaten des Raumes erneut gespeichert werden.
