### ISSUE TITLE
buildDateBoxes()

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#121]
In Bookings.php:

Wird die Funktion buildDateBoxes() noch benötigt? Schaut mir nach einer alten Default/Debug-Funktion aus...

**Comment by cassandre** [comment]
War mal eine alternative Darstellung der Datumsauswahl, die aber nur bei wenigen Auswahlmöglichkeiten sinnvoll ist. Im Prinzip eine hübsch gelayoutete Liste aller möglichen Slot/Sitz-Kombinationen als Radio-Buttons. Kann also eigentlich weg.
