### ISSUE TITLE
Workflow-Logik der Buchung konsolidieren

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-rsvp#124]
Z.B. eine Buchung, die schon ausgecheckt wurde, darf nicht mehr rückwirkend auf confirmed gestellt werden.

**Comment by cassandre** [comment]
Außerdem: E-Mail-Adresse für Bearbeitung sperren, da darüber die Personen identifiziert werden – sowohl gegen Doppelbuchungen, als auch in der Kontaktnachverfolgung.

**Comment by rvdforst** [comment]
Um Änderungen an den Metadaten von Buchungen einzuschränken oder sogar das Löschen durch den Raumverantwortliche zu vermeiden, muss die folgende Methode ergänzt werden: Actions::preBookingUpdate

**Comment by rvdforst** [comment]
Aktuelle Einschränkungen in der Buchungsliste:
- Wenn der Status "booked" ist, kann die Buchung bearbeitet werden
- Wenn der Buchungsstatus "booked", "confirmed" oder "cancelled" ist, kann der Status über die entsprechenden Schaltflächen geändert werden
- Wenn der Status der Buchung weder "checked-in" noch "checked-out" ist und auch die Buchung archiviert ist, kann die Buchung gelöscht werden

**Comment by xwolfde** [comment]
Kann zu, wurde mittlerweise umgesetzt
