### ISSUE TITLE
Buchungsmodus: Sprechstunden und Reservierung - E-Mailadresse für Raumverantwortliche zur Buchungsinfo und Freigabe 

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#128]
Derzeit wird bei Reservierungen und Sprechstundenbuchungen die E-Mail mit Benachrichtigung zur Buchung nur an die Mailadresse gesandt, welche in den Settings angegeben ist:
![grafik](https://user-images.githubusercontent.com/1070669/92569454-2e950b00-f270-11ea-84cd-49da41e173fd.png)

Es wäre schön, wenn man optional bei einem Raum (im Modus Sprechstunde oder Reservierung) einen "overwrite" durch eine dort angebbare Mailadresse geben könnte.
Dies wäre insbesondere bei  dem Modus der Sprechstunden sinnvoll, da hier nicht ein zentrale Raumverantwortlicher die Kontrollehaben möchte, sondern die jeweilige Person.

**Comment by rvdforst** [comment]
Derzeit ist es in der Einstellungen jedes Raums möglich, eine E-Mail-Adresse einzugeben, in der eine Kopie der bestätigten Reservierungen eingeht (Platzreservierung u. Sprechstunde):
<img width="1107" alt="Screenshot 2020-09-09 at 12 44 07" src="https://user-images.githubusercontent.com/299916/92589594-0d95df80-f29b-11ea-9822-d685d1712458.png">
