### ISSUE TITLE
Auschlusstage allgemein

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#136]
1. Eingabe von Einzelterminen an denen Reservierungsslots eingetragen werden sollen. 
Beispiel: Am Do, 10.9. von 10:00-12:00 sollen Termine reserviert werden können. Unabhängig davon ob auch sonst Donnerstags regelmäßig Termine möglich sind.

2. Ausschluss von Einzelterminen. 
Beispiel 1: Es ist allgemein eingetragen, dass immer Mittwochs von 9-13 Uhr Reservierungen möglich sind. Am Mittwoch dem 9.9. soll aber von 11-13 Uhr keine Reservierung möglich sein. 
Beispiel 2: Es ist allgemein eingetragen, dass immer Mittwochs von 9-13 Uhr Reservierungen möglich sind. Am Mittwoch dem 9.9. soll aber überhaupt keine Reservierung möglich sein.

3. Wochenpläne für unterschiedliche Datumsbereiche:
Beispiel: vom 14.9.2020 bis 20.9.2020 sollen Dienstags immer Reservierungen von 9-12 Uhr möglich sein, vom 21.9.20 bis 27.9.20 Dienstags aber immer von 13-16 Uhr.

**Comment by cassandre** [comment]
Punkt 2.1 finde ich etwas zu detailliert.
Punkt 1 wird ja schon durch Punkt 3 abgedeckt: Datumsbereich 10.9. bis 10.09.

**Comment by thenickless** [comment]
Testergebnis: 


Raum erstellt mit 

23.09.2020 bis 26.09.2020
Mo-So
12:00 - 13:00

28.09.2020 bis 30.09.2020
Mo-So
12:00 - 13:00

Days closed:
2020-09-24
2020-09-29


liefert über wp-admin/post-new.php?post_type=booking bei 

23.09.2020 : Für diesen Platz / Tag sind keine Termine verfügbar. (stimmt)
24.09.2020 : Für diesen Platz / Tag sind keine Termine verfügbar. (stimmt)
25.09.2020 : Für diesen Platz / Tag sind keine Termine verfügbar. (stimmt nicht)
26.09.2020 : Für diesen Platz / Tag sind keine Termine verfügbar. (stimmt nicht)
27.09.2020 : Für diesen Platz / Tag sind keine Termine verfügbar. (stimmt)
28.09.2020 : Terminauswahl (stimmt)
29.09.2020 : Für diesen Platz / Tag sind keine Termine verfügbar. (stimmt)
30.09.2020 : Terminauswahl (stimmt)

**Comment by thenickless** [comment]
gleiche Unstimmigkeit wie https://github.com/RRZE-Webteam/rrze-rsvp/issues/136#issuecomment-697355583 über Buchungsformular:

![ausschlusstage](https://user-images.githubusercontent.com/54806119/94017502-cf76e080-fdaf-11ea-81c9-a94c28585363.png)
