### ISSUE TITLE
Text bei Stornierung durch No-Show

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#137]
Der Text der Mail bei einer automatischen Stornierung bei einem No-Show erklärt nicht, warum die Stornierung erfolgte.
Damit sieht die Person, die zu spät kommt nicht, was sie falsch machte.

![grafik](https://user-images.githubusercontent.com/1070669/92882240-3fc05200-f3ff-11ea-9070-aeeffd4821cf.png)

Es wäre gut, wenn man für die Stornierung in Folge eines No-SHows noch mindestens einen erläuternden Extra-Satz ergänzt, wie bspw.: 
"Ihre Reservierung wurde 15 Minuten nach Beginn der Buchungszeit storniert, da Sie sich in dieser Zeit bislang nicht zum Platz eincheckten."

Vielleicht noch besser formulieren.

**Comment by thenickless** [comment]
umgesetzt in https://github.com/RRZE-Webteam/rrze-rsvp/commit/3bc1016000c1fcdf5e02be136000be29a6f7259d
