### ISSUE TITLE
Workflow für Seats und Rooms ergänzen

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-rsvp#140]
Gebuchte Seats und Rooms dürfen nicht gelöscht werden.

**Comment by rvdforst** [comment]
Aktuelle Einschränkungen in der Raumliste:
- Wenn dem Raum eine Reservierung zugeordnet ist, kann der Raum nicht gelöscht werden

Aktuelle Einschränkungen der Platzliste:
- Wenn dem Sitz einen Raum zugeordnet ist, kann der Platz nicht gelöscht werden
- Wenn dem Sitz einen Raum zugeordnet ist, kann kein anderer Raum für denselben Platz ausgewählt werden

**Comment by xwolfde** [comment]
Kann das geschlossen werden? Das ist doch schon umgesetzt, oder?

**Comment by cassandre** [comment]
Ja. Habe eben noch überprüft, ob auch Sitze nicht gelöscht werden können, denen eine Buchung zugeordnet ist. Das ist der Fall. Ich mache mal zu.
