### ISSUE TITLE
Check-In-Zeit einstellbar machen

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-rsvp#144]
z.B. UB:

> "Wir arbeiten im Moment mit 60 Minuten „Spielraum“, da wir einen Ansturm auf die Plätze zu Beginn eines Zeitslots verhindern wollen."

**Comment by cassandre** [comment]
Wurde auch in Ticket#2020100542001622 gefordert.

**Comment by xwolfde** [comment]
In Settings eine globaler Wert und zu den Räumen eine optionale Eingabe, wenn man den globalen Wert überschreiben will

**Comment by cassandre** [comment]
Nice-to-have: Es wäre für die Buchenden nützlich, diese Info in der Mail zu erhalten, dass sie bis zu Uhrzeit-X eingecheckt haben müssen.
