### ISSUE TITLE
Tests für V 1.0.0

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-rsvp#150]
- [x] Buchung ohne eMail-Adresse ist möglich : wp-admin/post-new.php?post_type=booking

gefixt in b9fa96adb017ea9815dbfbae1d016de5d2a85947

**Comment by thenickless** [comment]
- [ ] Notice: Trying to get property 'post_status' of non-object in /rrze-rsvp/includes/CPT/CPT.php on line 221 beim "Raum bearbeiten" : wp-admin/post.php?post=123456789&action=edit

**Comment by cassandre** [comment]
[ ] Änderungen an bereits bebuchten Plätzen werden nicht gespeichert. Das ist OK, allerdings wäre es besser, eine Bearbeitung erst gar nicht zuzulassen. Bzw. die Erfolgsmeldung "Beitrag gespeichert" zu ändern.

**Comment by thenickless** [comment]
- [ ] "Raum-Daten gehen verloren" : 
Vorgehensweise:

- Raum neu erstellen, Timeslots anlegen, Checkbox "automatisch bestätigen", Adresse eingeben, veröffentlichen

- Raum bearbeiten (über wp-admin/edit.php?post_type=room -> bearbeiten): alle eingebenen Daten sind vorhanden =  korrekt

- Plätze mit Platzgenerator zu diesem Raum erstellen ( wp-admin/tools.php?page=rrze-rsvp-tools ) A-Z, A-Z, Prefix = "nettes Plätzchen" : Plätze werden korrekt angelegt

- erneut Raum bearbeiten: Timeslots sind nicht mehr vorhanden, Adresse ist leer, Checkbox "automatisch bestätigen" ist nicht mehr angehakt

**Comment by thenickless** [comment]
Ergänzung zu https://github.com/RRZE-Webteam/rrze-rsvp/issues/150#issuecomment-694143107 : 

Und in der Buchungstabelle (wp-admin/edit.php?post_type=booking) sind daraufhin bereits vorhandene Buchungen diesem neuen Raum zugeordnet. Test auf sei.dev.cms. ... 

Die Plätze, die vorher in einem anderen Raum gebucht waren, hatten das gleiche Prefix bei der Erstellung mit dem Platzgenerator. Könnte eine Ursache sein, dass nicht IDs (eindeutig) sondern Namen (nicht eindeutig) verwendet werden?

**Comment by thenickless** [comment]
Ergänzung zu https://github.com/RRZE-Webteam/rrze-rsvp/issues/150#issuecomment-694143107 : 

Das sieht hier recht ähnlich aus: https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom&TicketID=829143

**Comment by thenickless** [comment]
- [ ] Bereits gebuchter Platz kann erneut gebucht werden. (gleicher Tag, gleicher Timeslot, gleicher Platz, gleicher Raum)

**Comment by rvdforst** [comment]
- [ ] Der Shortcode [rsvp-qr] zeigt nichts an.
templates/single-seat.php Z.341
echo do_shortcode('[rsvp-qr seat=' . $seatId . ']');

**Comment by thenickless** [comment]
> * [ ]  Der Shortcode [rsvp-qr] zeigt nichts an.
>   templates/single-seat.php Z.341
>   echo do_shortcode('[rsvp-qr seat=' . $seatId . ']');

Weil auf meinem Testserver im Moment der Link der Mail "Sie erhielten eine neue Reservierungsanfrage." zum Buchungsformular führt, kurzerhand soeben mit einer seatID als Beitrag mit dem Shortcode [rsvp-qr seat=123] getestet: funktioniert.
Darum: kannst du bitte explizit mit deiner $seatId mit einem Beitrag den Shortcode [rsvp-qr seat=123] testen? Der Shortcode versteht seat als slug als auch als ID.

**Comment by thenickless** [comment]
> * [ ]  Der Shortcode [rsvp-qr] zeigt nichts an.
>   templates/single-seat.php Z.341
>   echo do_shortcode('[rsvp-qr seat=' . $seatId . ']');



Ah, ich denke das ist gewollt und liegt nicht am Shortcode sondern am CSS:

```
        @media not print {
            display: none;
        }

```
in
```
.single-seat {
    .rsvp-qr-container {
        @media not print {
            display: none;
        }
        float: right;
        margin-left: 20px;
    }
}
```

Der Output vom Shortcode ist in diesem DIV:
`<div class="rsvp-qr-container"> ... </div>
`

**Comment by cassandre** [comment]
>     * [ ]  Bereits gebuchter Platz kann erneut gebucht werden. (gleicher Tag, gleicher Timeslot, gleicher Platz, gleicher Raum)

Aber nur im Backend, oder? Hatte ich mit Absicht so eingerichtet – manchmal will man so etwas überschreiben. Und die Warnung, dass da eigentlich kein Platz frei ist, wird ja angezeigt.

**Comment by thenickless** [comment]
- [ ] Buchung mit Start > Ende kann gebucht werden

**Comment by thenickless** [comment]
- [ ] Bereits gebuchter Platz kann gelöscht werden

**Comment by thenickless** [comment]
- [ ] Raum zu dem es Buchungen gibt, kann gelöscht werden

**Comment by thenickless** [comment]
- [ ] Fehler bei Sonderzeichen QR-PDF  ( wp-admin/edit.php?room=1234567890&generate_pdf )  

z.B.  liefert Platzgenerator &#8211; das im PDF als `&#8211;`  ausgeben wird

**Comment by rvdforst** [comment]
> > ```
> > * [ ]  Bereits gebuchter Platz kann erneut gebucht werden. (gleicher Tag, gleicher Timeslot, gleicher Platz, gleicher Raum)
> > ```
> 
> 
> Aber nur im Backend, oder? Hatte ich mit Absicht so eingerichtet – manchmal will man so etwas überschreiben. Und die Warnung, dass da eigentlich kein Platz frei ist, wird ja angezeigt.

Ja, nur Backend.

**Comment by thenickless** [comment]
- [ ] nice-to-have: drop-down "Platz" alphabetisch sortieren ( wp-admin/post-new.php?post_type=booking )

**Comment by thenickless** [comment]
> > > ```
> > > * [ ]  Bereits gebuchter Platz kann erneut gebucht werden. (gleicher Tag, gleicher Timeslot, gleicher Platz, gleicher Raum)
> > > ```
> > 
> > 
> > Aber nur im Backend, oder? Hatte ich mit Absicht so eingerichtet – manchmal will man so etwas überschreiben. Und die Warnung, dass da eigentlich kein Platz frei ist, wird ja angezeigt.
> 
> Ja, nur Backend.


ist offenbar gefixt. Tritt nicht mehr auf Tests mit https://github.com/RRZE-Webteam/rrze-rsvp/commit/b85ff1a5c965820f174c5a44dc61d064940c0c9e

**Comment by thenickless** [comment]
- [ ] Sortierung drop-down Räume im Buchungsformular

**Comment by thenickless** [comment]
- [ ] Sortierung drop-down Räume im Platzgenerator
