### ISSUE TITLE
Uhrzeiten-Felder bei "Buchung erstellen" entfernen

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-rsvp#153]
Auswahl der Start- und Ende-Uhrzeit nur über das Drop-Down "Termin auswählen" hat Vorteile:

- keine Plausibilitätsprüfung nötig (aktuell kann manuell zum gleichen Tag mit Start-Uhrzeit > Ende-Uhrzeit gebucht werden)
- Vereinfachung des Formulars (es soll ohnehin nur zu den Werten "Termin auswählen" gebucht werden können)

![Buchung-erstellen](https://user-images.githubusercontent.com/54806119/93599397-5eee4f00-f9be-11ea-8aba-c2027f428d6b.png)

**Comment by xwolfde** [comment]
In Zusammenhang mit #72
