### ISSUE TITLE
Buchung bestätigen durch Admin fehlerhaft

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#155]
Es wurde eine Reservierung gemacht.
Als Admin hab ich die dann im Backend manuell bestätigen wollen (da die E-Mail aus meinen Testsystem nicht rausging, aber das spielt ja keine ROlle).
Ich hab auch den Button "Bestätigen":
![grafik](https://user-images.githubusercontent.com/1070669/93771383-f3e68780-fc0c-11ea-8c28-e9b33d40b7ac.png)

Beim Klick auf den Button passiert allerdings nicht.

**Comment by thenickless** [comment]
Diesen Fehler kann ich nicht nachvollziehen. Sowohl auf unserem DEV-Server als auch auf dem nickless.test.rrze...-Server kann die Buchung im Admin per Button bestätigt werden.
=> verwendest du die aktuelle Version 1.0.0 ? 
=> gibt es eine Fehlermeldung im Logfile?

**Comment by xwolfde** [comment]
ok, ist wohl ein Problem meiner Installation. AUf Beta ist es auch richtig.
