### ISSUE TITLE
Raum-Filter in Buchungsliste funktioniert nicht

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-rsvp#156]
Vgl. Helpdesk Ticket#2020092142003576:
> in der Liste aller Buchungen soll man auch nach Räumen filtern können:
> Das klappt jedoch nicht. Filter nach Termin klappt, der Filter nach den Räumen liefert  kein Ergebnis.

**Comment by thenickless** [comment]
gefixt in https://github.com/RRZE-Webteam/rrze-rsvp/commit/2c0d92fedb67664d818938451a864289fb626eae

**Comment by uliried** [comment]
Der Filter "Alle Räume anzeigen" funktioniert bei uns leider noch nicht richtig, nur für die zuletzt angelegten Räume

**Comment by thenickless** [comment]
gefixt in https://github.com/RRZE-Webteam/rrze-rsvp/commit/e58781375d51b7d7a3408fe898521f4e9fbcba42
