### ISSUE TITLE
Settings-Reset

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#159]
Wenn aus verschiedenen Gründen die Settings nicht mehr passen, wäre ein Reset der Settings auf die Defaults des  Auslieferungszustand schön.

Nice to have, aber nicht wichtig.

**Comment by thenickless** [comment]
umgesetzt in https://github.com/RRZE-Webteam/rrze-rsvp/commit/8f725a8dbcd01d7313f95ba5916715580bcc4d51
