### ISSUE TITLE
Reservierungsbestätigung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#16]
Personen, die eine Reservierung vornehmen, erhalten eine Mailbestätigung mit den notwendigen Angaben, ggf. müssen die Mail auch nochmals bestätigen.

Wenn nicht bestätigt wird, verfällt die Reservierung automatisch nach xx Minuten (Vorschlag für xx = 60).

Der Raumadmin kann diese Funktion (der Zwang zur Bestätigung) abschalten. Per default sollte sie aber an sein.

**Comment by xwolfde** [comment]
testen

**Comment by xwolfde** [comment]
geht das schon?

**Comment by rvdforst** [comment]
Nein, weil CronJob ist noch nicht fertig.

**Comment by rvdforst** [comment]
Ist erledigt. Version 0.1.4-0 (branch prototyp)
