### ISSUE TITLE
Erzwungene SSO-Anmeldung ohne "SSO erforderlich"

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-rsvp#164]
Wenn das FAU WebSSO-Plugin aktiviert ist, muss man sich über SSO anmelden, auch wenn die Option "SSO erforderlich" bei dem Raum nicht aktiviert ist.

**Comment by thenickless** [comment]
Bei der Erstellung des Raums wird der Shortcode in der Metabox als 

`[rsvp-booking room="123456789" sso="true"]`

ausgegeben - unabhängig davon, ob die Option "SSO erforderlich" gewählt ist.

**Comment by cassandre** [comment]
in https://github.com/RRZE-Webteam/rrze-rsvp/commit/8197846a062ac5c416e0dd4361457aa24954d9fb gefixt.
