### ISSUE TITLE
gebuchte Timeslots dürfen nicht verändert werden

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-rsvp#165]
Aktuell können über "Raum bearbeiten" die Timeslots verändert und gelöscht werden, unabhängig davon, ob sie bereits in Buchungen verwendet werden.

**Comment by cassandre** [comment]
Ist jetzt so umgesetzt, dass nur Wochentag und Start-/Endzeit nicht verändert werden dürfen, sobald es Buchungen für diesen Timeslot gibt. **Start- und Enddatum können weiterhin verändert werden**, sonst könnte z.B. ein einmal bebuchter "endloser" Timeslot nie wieder beendet werden.

-> TODO: ggf. Start- und Enddatum beim Speichern überprüfen: Wurde es verändert, und gibt es Buchungen, die von dieser Veränderung betroffen wären (Buchungsdatum nach neuem Enddatum oder vor neuem Startdatum)?

**Comment by cassandre** [comment]
Commit 5518fa7 löst TODO aus  Kommentar oben (https://github.com/RRZE-Webteam/rrze-rsvp/issues/165#issuecomment-703821638).
