### ISSUE TITLE
Aktuelle Raumbelegung ggf. ausblenden

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-rsvp#172]
Endpoint Room: Wenn keine Sitze angelegt -> Accordion Aktuelle Raumbelegung weglassen oder entsprechende Meldung (statt leerer Tabelle)

**Comment by thenickless** [comment]
Das wurde mit der Ausgabe "In diesem Raum gibt es heute keine freien Plätze." bereits gelöst.
