### ISSUE TITLE
Telefonnummer kein Pflichtfeld

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-rsvp#177]
Bitte vom Personalrat: Telefonnummer bitte keine Pflichtfeld mehr. Nur noch Optional.

**Comment by xwolfde** [comment]
Ist auch nun mit Datenschutz abgestimmt. Kann/Sollte also optional werden.

**Comment by thenickless** [comment]
Bug: auf wp-admin/post-new.php?post_type=booking&wp-post-new-reload=true ist es noch Pflichtfeld
