### ISSUE TITLE
Suche zur Kontaktverfolgung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#178]
Derzeit kann nur nach E-Mailadresse gesucht werden.
Wir brauchen auch eine Suchmöglichkeit nach Telefonnummer (auch wenn diese nur optional ist)

**Comment by cassandre** [comment]
Wie gut, dass es eine Git-History gibt. ;-)

**Comment by thenickless** [comment]
umgesetzt in https://github.com/RRZE-Webteam/rrze-rsvp/commit/99a513c17c19849c58939d36dbff78b4c74b80c4

Suche kann entweder nach eMail oder Tel oder eMail und Tel erfolgen:

Beispiele:

eMail ist auffindbar, Tel ist leer: Treffer
eMail ist nicht auffindbar, Tel ist auffindbar: Treffer
eMail ist leer, Tel ist leer: kein Treffer
eMail ist nicht auffindbar, Tel ist leer: kein Treffer
eMail ist nicht auffindbar, Tel ist nicht auffindbar: kein Treffer
eMail ist auffindbar, Tel ist auffindbar: Treffer, aber diese können aber müssen nicht bedeuten, dass eMail UND Tel auffindbar sind. eMail-Adresse MUSS nicht zum User mit der gesuchten Telefonnummer gehören. Kann, aber muss nicht. (OR in SQL)

D.h. entweder eMail oder Tel wird gefunden, unabhängig davon welche Eingabe (eMail oder Tel) die richtige ist.
