### ISSUE TITLE
Platzinfozettel mit QR-Codes

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#18]
Die Raumadmins die Räume anlegen erhalten die Möglichkeit, für jeden einzelnen Platz in dem Raum ein DInA4 Zettel auszudrucken. Auf diesem Zettel ist ein QR-Code und eine ShortURL für die Anmeldung/Abmeldung. Die Zettel sollen ausgedruckt werden und an jeden einzelnen Platz geklebt werden.

**Comment by xwolfde** [comment]
Auf CMS Instanzservern derzeit nicht möglich. Ursachensuche ongoing.

**Comment by rvdforst** [comment]
Solved! Vgl. commit c53d8772f5e96ecfc4bc3f3aaa4638b92e37c371
