### ISSUE TITLE
Beschreibung der Buchungsmodi ergänzen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#180]
![grafik](https://user-images.githubusercontent.com/1070669/94813274-5139c000-03e7-11eb-90f9-62b46d46dae6.png)

In der Beschreibung ggf. ergänzen:

"Der Buchungsmodus legt das grundlegende Workflow für eine Buchung fest:
   - Sprechstunde:  Diese Modus enthält nur die Registrierung und Anmeldung  für einen Termin und einem Platz. Es erfolgt jedoch kein Einchecken und Auschecken am Platz und somit keine Kontaktverfolgung.
       Dieser Modus eignen sich insbesondere dann, wenn man Räume der sogenannten Positivliste nutzt, in der bereits die Kontaktverfolgung durch darfichrein.de erfolgt."

   - Platzreservierung: In diesem Modus wird die Registrierung und Anmeldung  für einen Termin und einem Platz durchgeführt plus zusätzlich beim Erreichen des Termins das Einchecken und Auschecken am Platz. Hierbei werden Daten der Teilnehmer zur Kontaktverfolgung gespeichert. 

  - Nur Einchecken und Auschecken am Platz: In diesem Modus wird keine Vorabreservierung von Plätzen angeboten. Dieser Modus eignen sich nur für die reine Kontaktverfolgung und Platzbuchung am Platze. 
An der FAU sollte dieser Modus nur für Räume oder Ressourcen verwendet werden, die nicht bereits durch die Anwendung darfichrein.de verwaltet werden.

"

**Comment by thenickless** [comment]
Typos gefixt:

![grafik](https://user-images.githubusercontent.com/1070669/94813274-5139c000-03e7-11eb-90f9-62b46d46dae6.png)

In der Beschreibung ggf. ergänzen:

"Der Buchungsmodus legt den grundlegenden Workflow für eine Buchung fest:
   - Sprechstunde:  Diese Modus enthält nur die Registrierung und Anmeldung für einen Termin und einen Platz. Es erfolgt jedoch kein Einchecken und Auschecken am Platz und somit keine Kontaktverfolgung.
       Dieser Modus eignet sich insbesondere dann, wenn man Räume der sogenannten Positivliste nutzt, in der bereits die Kontaktverfolgung durch darfichrein.de erfolgt."

   - Platzreservierung: In diesem Modus wird die Registrierung und Anmeldung für einen Termin und einen Platz durchgeführt plus zusätzlich beim Erreichen des Termins das Einchecken und Auschecken am Platz. Hierbei werden Daten der Teilnehmer zur Kontaktverfolgung gespeichert. 

  - Nur Einchecken und Auschecken am Platz: In diesem Modus wird keine Vorabreservierung von Plätzen angeboten. Dieser Modus eignet sich nur für die reine Kontaktverfolgung und Platzbuchung am Platze. 
An der FAU sollte dieser Modus nur für Räume oder Ressourcen verwendet werden, die nicht bereits durch die Anwendung darfichrein.de verwaltet werden.

"
