### ISSUE TITLE
Check-In per Button auf Seat-Seite funktioniert nicht

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-rsvp#183]
Ruft wieder die gleiche Seat-Seite mit GET-Param ?id=$BookingId&action=checkin auf -> Nachricht mit Check-In-Aufforderung und -Button wird wieder angezeigt. Buchung wird intern auch nicht auf Checked-In gesetzt.

Check-In per Button in Mail auf die selbe Buchung funktioniert.

**Comment by uliried** [comment]
Ich kann den Fehler in unserer Installation nicht nachvollziehen. Wir hatten das gleiche Problem Anfang der Woche in einem Raum, bei dem ein Zeitslot neu angelegt wurde, so lange die Fehler bei der Darstellung der Slots bestanden. Der Slot musste nach dem Update neu angelegt werden, danach trat kein Fehler mehr auf
