### ISSUE TITLE
Dashboard-Fehler nach Deaktivierung des Plugins

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#187]
Wenn bei einer bestehenden Buchung das Plugin deaktiviert wurde, ist danach die Dashboard der Website nicht mehr aufrufbar!

vgl Tickets 2020100642003253  und 2020100142001657

Bitte umgehend nachgehen.

**Comment by rvdforst** [comment]
Der Fehler wurde behoben. Vgl. 36300ea3bb220b2fa137f3c28dd57e6891e05f2b
