### ISSUE TITLE
Abruf Raumbelegung für Raumadmins

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#19]
Raumadmins sollen eine Ansicht haben mit der die getätigten Buchungen eingesehen werden können. Möglichst in einer Übersicht, in der Tag (des gebuchten Termins, nicht Bestelldatum) und Uhrzeit des Slots zu sehen sind. Alternativ eine Möglichkeit, sich eine Übersicht dieser Termine per E-Mail zuschicken lassen.

**Comment by xwolfde** [comment]
Ist in der Buchungsübersicht. Die Filterung muss noch komfortabler gemacht werden.

**Comment by thenickless** [comment]
Umgesetzt sind mit https://github.com/RRZE-Webteam/rrze-rsvp/commit/c1ff25cc118ecd0c926379bc3ab23f827f1d14df

- Backend: /wp-admin/edit.php?post_type=booking&page=rrze-rsvp
- Frontend: /room/ $roomSlug /?format=embedded

In Arbeit ist die Filterung nach "room" und "date": /wp-admin/edit.php?post_type=booking

**Comment by thenickless** [comment]
2DO:
- Backend / Frontend von https://github.com/RRZE-Webteam/rrze-rsvp/issues/19#issuecomment-673959509 um Info ergänzen, damit RaumAdmin sehen kann, dass Platz belegt und gebucht, aber Person nicht eingecheckt ist:

aktuell wird getSeatAvailability() verwendet

  'key' => 'rrze-rsvp-booking-status',
                    'value'   => ['confirmed', 'checked-in'],
                    'compare' => 'IN'

Fazit: aufschlüsseln, ob 'confirmed' oder 'checked-in' 

Layout mit 
- grün = frei
- blau = gebucht und eingecheckt
- rot = gebucht, aber nicht eingecheckt

**Comment by thenickless** [comment]
Umgesetzt in https://github.com/RRZE-Webteam/rrze-rsvp/commit/e764941d1326aa0b123af731f97adb1752ed3bcb
