### ISSUE TITLE
REST API testen

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-rsvp#193]
- REST API Doku: https://developer.wordpress.org/rest-api/
- ( Sicherheitsbedenken: https://www.wpwhitesecurity.com/wordpress-rest-api-and-the-security-worries/ )
- ( Automatisierte Tests: https://deliciousbrains.com/automated-api-testing-codeception-wordpress/ (+ Open Source Alternativen) )

Fragestellungen:
Endpoints? CPT, Tax, .. ?

- https://developer.wordpress.org/reference/functions/register_post_type/
- https://developer.wordpress.org/reference/functions/register_taxonomy/
- https://developer.wordpress.org/reference/functions/register_rest_route/
- https://developer.wordpress.org/reference/functions/register_rest_field/

**Comment by xwolfde** [comment]
wurde geprüft (auch von extern). in Ordnung
