### ISSUE TITLE
html-IDs in Shortcodes entfernen

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-rsvp#194]
... da mehrere Shortcodes auf einer Seite eingebunden werden können (v.a. rrze-availability)
https://www.theologie.fau.de/belegungsplan/#occupancy ist zwar als Feature schön, aber semantisch falsch.

**Comment by thenickless** [comment]
Ist "data-name="occupancy"" mit "html-IDs" gemeint?
Dass alles aufgeklappt lädt, bietet eine gute Übersicht.

**Comment by cassandre** [comment]
OK, stimmt, ist das name=""-Attribut. Dann passt das.
