### ISSUE TITLE
Filter-Möglichkeiten in Buchungsliste

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-rsvp#198]
"Dann hätte ich noch einen GROßEN Wunsch :wink:. Den fehlerhaften Filter in der Buchungsliste habe ich ja bereits gemeldet. Es wäre uns zusätzlich eine große Hilfe, wenn man 1. in der Liste doch auch nach Namen und Sitzplatz suchen und 2. vielleicht auch der Zeitslot im Filter "Alle Termine anzeigen" stehen könnte. Wir haben mittlerweile fast 5000 Buchungen, der Filter nach Terminen zeigt uns pro Tag 6 Einträge an, da muss man erst mal den richtigen finden. Bei dem Filter ab 8:00 haben wir 20 Seiten, wenn man da einen bestimmten Eintrag zum Einchecken sucht, blättert man ziemlich ..."

**Comment by thenickless** [comment]
Die Suche funktioniert bei Buchungen nicht. Unklar, was post_title sein mag. Aber unwichtig, da Suchfunktion die Metas einschliessen sollte.

- interessante Lsg: https://wordpress.stackexchange.com/questions/78649/using-meta-query-meta-query-with-a-search-query-s

**Comment by xwolfde** [comment]
ref #156

**Comment by thenickless** [comment]
umgesetzt in https://github.com/RRZE-Webteam/rrze-rsvp/commit/e58781375d51b7d7a3408fe898521f4e9fbcba42
