### ISSUE TITLE
SSO-Anmeldung kann gelegentlich Probleme Verursachen

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/rrze-rsvp#199]
Fehlermeldung durch Kunden:
Bei manchen Geräten kann es vorkommen, dass die SSO-Anmeldung übergangen wird, wenn die Benutzer bereits vorher einen Platz im gleichen Haus reserviert haben. (Fall: Ohne Reservierung, Check-In am Platz). 
Wenn man dann eincheckt, wird in seltenen Fällen auf die vorherig geöffnete Seite zurückgeleitet, man erhält keine Bestätigungsmail und der Platz wird im System nicht besetzt.

Fehler konnte durch Melder nicht ein zweites mal reproduziert werden.
Cookies löschen scheint teils zu helfen.

Alle Informationen zum Fall: http://go.fau.de/9ptgz

**Comment by ej64ojyw** [comment]
Ergänzungen über Helpdesk:
"danke für die Rückmeldung. Nur noch als Ergänzung: ich hatte eben denselben Fehler noch einmal (mit Firefox). Nur reichte es nicht, die Cookies zu löschen, sondern ich habe alle Browserdaten gelöscht (also Websitedaten, Chronik und Websiteberechtigungen). Dann ging es wieder."

**Comment by xwolfde** [comment]
Benjamin, kannst du schauen ob das noch aktuell ist? Ich vermute aufgrund des Alters und der gemachten Arbeiten auf dem Gebiet, dass es schon obsolet ist

**Comment by thenickless** [comment]
Fehler taucht in 2.0.7 nicht mehr auf. Es wird unmittelbar nach Login ausgeloggt.
