### ISSUE TITLE
Aktuelle Raumbelegung auf der Website und auf Public Display

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#20]
Es besteht der Wunsch, eine Anzeige der Räumbelegung für Public Displays anzubieten. Insbesondere die UB bekräftigte diesen Wunsch. Also: Pro Raum eine URL in der man die aktuelle Belegung sehen kann. Exportierbar für Public Display und Webseite

**Comment by cassandre** [comment]
Umgesetzt in e244bcba6e2e4fa7a2aa81d1bee81d74427fcb26, 61d4d5a7afe664ff93c064a87667cea6065ead52 und 6aa193526c416233697c01ae24aebfdcee3e1eb7:

$domain/room/$roomslug/...
`?format=embedded&show=info` => Content und Thumbnail
`?format=embedded&show=schedule` => Wochenplan
`?format=embedded&show=availability` => Verfügbarkeit 10 Tage
`?format=embedded&show=occupancy` => Raumbelegung heute
`?format=embedded&show=occupancy_now` => Raumbelegung heute ab jetzt (keine vergangenen Timeslots)
`?format=embedded&show=occupancy_nextavailable` => Nächste verfügbare Plätze
`?format=embedded&show=floorplan` => Grundriss

Kann ergänzt werden durch `&width=1234` bzw. `&height=1234` um die Ausgabe für die Größe des Display-Layouts zu optimieren.
