### ISSUE TITLE
Workflow Bestätigung konsolidieren

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-rsvp#202]
-> zusätzlicher Status (Unterschied Bestätigung durch Bucher oder Admin
-> Label Bestätigung Admin klarer (ggf. Checkbox umdrehen)
-> Actions anpassen

**Comment by cassandre** [comment]
Außerdem: Kunde bekommt bisher keine Mail, wenn Buchung durch Admin bestätigt werden muss. -> ergänzen

**Comment by xwolfde** [comment]
Ist das noch aktuell?

**Comment by cassandre** [comment]
Ist mit dem kommenden Update diese Woche erledigt.
