### ISSUE TITLE
Neue Option: Platzreservierung ohne Check-In

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-rsvp#203]
-> Dropdown im Raum ergänzen
-> schaltet CheckIn-Required-Checkbox aus
-> versteckt alle CheckIn-Optionen
-> Mailtexte anpassen

**Comment by xwolfde** [comment]
Die Option im Nuchungsmodus ist auf master offenbar schon  ausgerollt. 
Kann der Issue dann geschlossen werden?

**Comment by cassandre** [comment]
Jepp.
