### ISSUE TITLE
Beim Filtern nach Raum in Buchungsübersicht werden nicht alle gebuchten Plätze angezeigt

### ISSUE THREAD

**Issue by tmaiwald** [RRZE-Webteam/rrze-rsvp#207]
![issue_filter](https://user-images.githubusercontent.com/10143508/97193738-9d3f1100-17a9-11eb-8cc5-944d54df005d.png)
Obwohl auch andere Plätze in den jeweiligen Räumen gebucht wurden, wird bei der Filterung Filter nur ein Platz angezeigt (z.B. wird wie im Bild nur Platz A1 angezeigt, obwohl an den selben Tagen auch B1 gebucht wurde)

**Comment by thenickless** [comment]
gefixt in https://github.com/RRZE-Webteam/rrze-rsvp/commit/e58781375d51b7d7a3408fe898521f4e9fbcba42
