### ISSUE TITLE
In der Buchungsübersicht tauchen im Terminfilter die Daten mehrfach auf

### ISSUE THREAD

**Issue by tmaiwald** [RRZE-Webteam/rrze-rsvp#208]
![image](https://user-images.githubusercontent.com/10143508/97194488-7c2af000-17aa-11eb-89d8-f55e509162f6.png)

**Comment by thenickless** [comment]
gefixt in https://github.com/RRZE-Webteam/rrze-rsvp/commit/e58781375d51b7d7a3408fe898521f4e9fbcba42
