### ISSUE TITLE
Permalink "__trashed" trotz abgebrochener Löschung

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-rsvp#210]
Bereits gebuchten Raum oder Platz über den Link "In den Papierkorb verschieben" in der im Edit-Screen löschen
-> Löschung wird mit entsprechender Meldung abgebrochen
-> Zurückgeleitet zum Edit-Screen
-> Permalink des Raums oder Platzes bekommt "__trashed" angehängt.

**Comment by thenickless** [comment]
gefixt in https://github.com/RRZE-Webteam/rrze-rsvp/commit/6353f84679134b4d04266b51bb7d05843d8c775e

(Info: verantwortlich dafür ist wp_add_trashed_suffix_to_post_name_for_post() - leider ist diese Funktion private und kann nicht umgangen werden. Lsg:             
`$wpdb->update( $wpdb->posts, array( 'post_name' => $post_data['post_title'] ), array( 'ID' => $post_id ) );
`
