### ISSUE TITLE
Sortierung Plätze

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#217]
Die Anzeige der verfügbaren Plätze ist nicht korrekt. 
Plätze werden
- teilweise nur alphabetisch sortiert
![grafik](https://user-images.githubusercontent.com/1070669/98093469-e7965100-1e7f-11eb-860f-96c1cabdfec2.png)

- teilweise nach Anlegedatum
![grafik](https://user-images.githubusercontent.com/1070669/98093501-eebd5f00-1e7f-11eb-93a1-e5eb132a12f2.png)

Ausgabe und Sortierung sollte besser mit dem Sort-Flag SORT_NATURAL  gemacht werden

Ref #79

**Comment by thenickless** [comment]
Gefixt in https://github.com/RRZE-Webteam/rrze-rsvp/commit/73d05c8eb8f82d6be8d0751c2d003614a6a3a64b 

- Bookings.php buildSeatSelect()
- Functions.php getOccupancyByRoomId()
