### ISSUE TITLE
Erinnerungsfunktionen für Bucher

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#22]
Für Personen, die eine Vorab-Reservierung getätigt haben, werden in Festgelegten Abständen E-Mails zur Erinnerung gesandt.

**Comment by rvdforst** [comment]
Ich bin mir nicht sicher, ob wir Erinnerungen an Personen senden. Es sieht aus wie Spam. Außerdem müssten wir eine Mailing-Queue entwickeln, um WP nicht zu überlasten. Die an den Bucher gesendete Kalenderdatei (ICS) reicht nicht aus?

**Comment by xwolfde** [comment]
Stellen wir zurück auf Version 2, da wir wegen den Queuing gegen Spam nochmal nachdenken müssen

**Comment by xwolfde** [comment]
Nehmen wir erstmal raus. Die Kalenderdatei sollte reichen, da diese den eigenen Kalender dazu bringt das selbst zu machen.
