### ISSUE TITLE
Zurücksetzen prüft nicht, ob bereits Platz gebucht ist

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-rsvp#234]
Mit "Zurücksetzen" kann derzeit ein Platz mehrfach vergeben werden.

Es fehlen folgende Prüfungen:
- ist Zurücksetzen-Platz noch verfügbar?
- Hat Zurücksetzen-Person bereits einen Platz im Slot im Raum?

**Comment by xwolfde** [comment]
Ist das noch aktuell?

**Comment by thenickless** [comment]
Ja, Fehler besteht auch in 2.0.7 noch

**Comment by thenickless** [comment]
d.h. es wird nur eine Mail an Bucher geschickt. In der Buchungsübersicht sind jedoch die mehrfachen Buchungen zur gleichen Person zum gleichen Timeslot auf den gleichen Platz aufgelistet.

**Comment by xwolfde** [comment]
Ist der Bug noch offen? Wenn nein, bitte schließen

**Comment by thenickless** [comment]
"Zurücksetzen" wurde mit Version 2.6.12 deaktiviert und kann daher keine Fehler mehr verursachen. https://github.com/RRZE-Webteam/rrze-rsvp/commit/2e8991614188cbc0cc99fdf7b50599206b87d1a2
