### ISSUE TITLE
SSO-Authent. kann umgangen werden (Helpdesk)

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/rrze-rsvp#235]
Kurzbeschreibung:
Wenn ein Raum mit SSO Authent. markiert wird, funktioniert diese korrekt auf der speziellen Raum-Buchungsseite. Jedoch kann man sich auf dem zweiten Buchungsformular, welches sich in diesem Helpdesk-Fall auf der Startseite befindet frei ohne SSO-Authent. für einen Timeslot einbuchen.

Helpdesk-Ticket mit Fallbeispiel und genauen Details: http://go.fau.de/9p1gk

**Comment by xwolfde** [comment]
Ist das nicht schon behoben?

**Comment by cassandre** [comment]
Müsste sein, da mittlerweile nach dem Buchen ja sofort ausgeloggt wird. Man sollte die Leute nur drauf hinweisen, dass das Shortcode-Attribut sso=true abgeschafft wurde, und nur noch die Authentifizierungs-Optionen des Raumes gelten.

**Comment by thenickless** [comment]
Ist in 2.0.7 behoben. Shortcode wird unter "Raum bearbeiten" korrekt ohne sso-Attribut angezeigt.
