### ISSUE TITLE
Buchung: Admin-Bestätigung möglich, bevor eMail-Adr verifiziert wurde

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-rsvp#238]
Buchung kann in /wp-admin/edit.php?post_type=booking bestätigt werden, obwohl die Buchung vom Besucher noch nicht bestätigt wurde (eMail „Bitte bestätigen Sie Ihre Buchung)

**Comment by cassandre** [comment]
Erübrigt sich mit den Änderungen der E-Mail-Branch.

**Comment by xwolfde** [comment]
Kann der Fall geschlossen werden?

**Comment by thenickless** [comment]
Ist in 2.0.7 behoben.
