### ISSUE TITLE
Anmeldung via UB-AD

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#24]
Auch UB-Card-Besitzer müssen rein (UB-AD) kommen können.

**Comment by thenickless** [comment]
Ist diesr Vorschlag gut?

1. Anstelle der Checkbox "SSO is required" ein Radiobutton mit den Werten:

- SSO 
- LDAP
- ohne Anmeldung (default)


2. neuer Reiter unter wp-admin/options-general.php?page=rrze-rsvp mit Beschriftung "LDAP" mit einem Eingabefeld für den Server-URL

**Comment by thenickless** [comment]
Für Tests in https://github.com/RRZE-Webteam/rrze-rsvp/commit/b29cc1e326d0e4737616eb9abd8e5542a4699db6 als Shortcode [rsvp-ldap-test] 
- LDAP-Settings in wp-admin/options-general.php?page=rrze-rsvp&current-tab=rrze-rsvp-ldap
- gibt Infos über rrze-log aus: /wp-admin/network/admin.php?page=rrze-log aus

Offene Fragen:

- [ ] erhaltene Zugangsdaten stimmen nicht (ldap_bind() liefert Error Nr. 49 "Invalid credentials")
- [ ] muss Username bei ldap_bind() mit Domain übergeben werden?
Falls ja: durch // oder @ getrennt? (alle 7 Testvarianten liefern Error Nr. 49 "Invalid credentials")

**Comment by thenickless** [comment]
- [ ] set email after return

**Comment by xwolfde** [comment]
> Ist dieser Vorschlag gut?

Ich würde lieber eine Auswahlliste nehmen statt Radiobuttons.
Und: Die Liste der Optionen soll abhängig von gesetzten Parametern im den Settings (bzgl. LDAP) oder der Existenz des SSO-Plugins sein.
Sprich: 
- Die FAU SSO-Option  soll nur erscheinen, wenn das Plugin auch existiert.
- Die LDAP-Option soll nur erscheinen, wenn in den RSVP Settings auch LDAP-Parameter vollständig ausgefüllt wurden

**Comment by cassandre** [comment]
> Ist dieser Vorschlag gut?

Laut UB muss für einen Raum sowohl SSO als auch LDAP gleichzeitig möglich sein (eigentlich auch logisch). D.h. wir brauchen noch eine dem Formular vorgeschaltete Abfrage "Wie möchten Sie sich authentifizieren?".
