### ISSUE TITLE
Raum-E-Mail-Adresse auch für Stornierungen und Co. verwenden

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-rsvp#244]
Um das RSVP-Tool auch für Sprechstunden zu nutzen, muss man einzelne Personen als Raum mit Sitzplatz anlegen. Man kann dann jeweils eine E-Mail-Adresse anlegen.

An diese E-Mail-Adresse wird aber nur die bestätigte Buchung in Kopie verschickt. Die Stornierung und auch die Bestätigung läuft nur über die zentrale Mail-Adresse. Das macht es für große Webseiten wie fau.de schwierig das Tool zu nutzen, weil es keine zentrale E-Mail-Adresse geben kann, die Sprechstunden für mehrere Abteilungen koordiniert.

Es wäre deshalb klasse, wenn entweder:
1. Die Raum-E-Mail-Adresse alle Mails in Kopie bekommen würde.
oder
2. Es eine Einstellung gibt, die es ermöglicht, dass Bestätigungen, Stornierungen etc. direkt über die Raum-E-Mail-Adresse laufen. So könnte die Person gleich alles selbst klären.

**Comment by xwolfde** [comment]
Gute Vorschlag. Nehmen wir auf für den nächsten Milestone.

**Comment by thenickless** [comment]
Sobald umgesetzt ist, informieren: https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom;TicketID=934226;ArticleID=2980492
