### ISSUE TITLE
ICS Datei für Raumverantwortlichen um Buchenden ergänzen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#253]
Feature Request via Mail:
> Für einige Arbeitsplätze haben wir bisher schon Kalender geführt und die 
> Benutzer haben per Mail, etc. Termine mit den jeweiligen Gerätebetreuern 
> ausgemacht. D.h. es sind schon Kalender vorhanden. Da ist es sehr schön, 
> dass RSVP auch .ics-Dateien verschickt. Wäre es möglich, dass RSVP auch 
> den Namen des Buchenden mit in den ICS-Eintrag schreibt? Das ist, wie 
> gesagt, nur für unsere interne Buchführung bzw. Historie.

**Comment by cassandre** [comment]
Was sagt der Datenschützer dazu?

**Comment by xwolfde** [comment]
Ich werde das mal bei unserem nächsten Treffen mit dem DSB ansprechen.
Das jemand der eine SPrechstunde ausführt, auch den termin inkl. dem Namen der Person die dabei ist, im Kalender speichern möchte ist naheliegend.
Wenn wir uns dem Wunsch verweigern, könnte hingegen die Gefahr bestehen, dass die Sprechstundenleute sich eben ein Admin-Zugang "erfordern" und dann können sie alles sehen...

**Comment by thenickless** [comment]
wurde mit https://github.com/RRZE-Webteam/rrze-rsvp/issues/310 umgesetzt
