### ISSUE TITLE
Anwesenheitsbestätigung - Einbuchen vor Ort

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#26]
Jeder, der einen Platzt besetzt, muss sich vor Ort einbuchen.
Dazu ruft er eine Website auf, die via QR-Code auf dem Tisch bekannt gegeben ist.

Dies gilt auch für Leute, die den Platz reserviert haben.

**Comment by xwolfde** [comment]
Ruft via Code die Sitzplatzseite auf.

Die Sitzplatzseite zeigt folgendes:


Wenn man noch nicht via SSO eingeloggt ist:

Wenn noch niemand zur aktuellen Zeit eingecheckt ist:
      Jetzt einchecken
    
        Dann erfolgt eine Umleitung zu SSO und es wird geprüft ob man einchecken kann und wird dann ggf.eingecheckt


Wenn bereits jemand eingecheckt ist:

     "Der Platz ist bereits besetzt.       Jetzt auschecken"
        
   => Auch zu SSO und prüfen ob die Person die selbe ist. Wenn ja, dann auschecken.





Wenn man via SSO eingeloggt ist:
  Prüfen ob der Platz mit jemand anderen besetzt ist:

      "   Der Platz ist bereits reserviert.   "

  Wenn er noch nicht reserviert ist oder man hat ihn selbst reserviert, ist aber noch nicht eingecheckt:
   
       "Jetzt einchecken"

Zusätzlich: Wenn man den PLatz reserviert hat, aber noch nicht eingecheckt hat:
     
      "Platz freigeben"


Wenn man schon eingecheckt ist:

    "Jetzt auschecken"



  




   
Button:   Jetzt einchecken

**Comment by cassandre** [comment]
Ist eigentlich schon genauso umgesetzt. Oder kommt es dir auf den Wortlaut der Hinweise an?
Außerhalb der Öffnungszeiten des Raumes wird kein Button angezeigt.

**Comment by xwolfde** [comment]
Nö, der Issue war primär dokumentarisch, damit der Prozess wo steht.
Kannst zumachen, wenn es geht.
