### ISSUE TITLE
Element Id doppelt

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#263]
Im Anmeldeformular wird eine Id rrze_rsvp_post_nonce_field  doppelt genutzt:

![grafik](https://user-images.githubusercontent.com/1070669/115544536-3e5ae000-a292-11eb-81de-abf7c8b5d392.png)

**Comment by thenickless** [comment]
reopened for me

**Comment by thenickless** [comment]
Gefixt. Ursache: Parameter $echo in wp_nonce_field() war nicht gesetzt. Da default TRUE ist und die Funktion in einem String verwendet wurde, der mit echo() ausgegeben wurde, wurde das Feld doppelt generiert.
