### ISSUE TITLE
Sitzplatzgenerator

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/rrze-rsvp#280]
Hallo, ich soll das Plug-in für das Wintersemester testen, wenn/falls hybride Vorlesungen durchgeführt werden sollen. Ich bin jetzt auf folgendes Problem gestoßen.

Ich möchte natürlich nicht jeden Sitzplatz einzeln anlegen müssen. Aber der Generator ist für unsere Bedürfnisse nur bedingt geeignet. 

Folgendes Szenario: 

In unserem Hörsaal C2 sind z. B. insgesamt 25 Plätze möglich. Insgesamt gibt es 10 Reihen mit 198 Sitzplätzen (in der hintersten Reihe fehlen 2 Plätze wegen Beamervorrichtung o.ä.). Die Plätze sind aber so angeordnet, dass in der 1. Reihe nur 5 Plätze von 20 Plätze verfügbar sind, in der 2. Reihe gar keine, dann in der 3. Reihe wieder 5 von 20 Plätzen. Also jede gerade Reihe ist leer. Es sind somit letztlich nur 5 Reihen mit jeweils 5 Plätzen belegbar. Hinzu kommt, dass im Hörsaalplan, den wir von der AG Arbeitssicherheit erhalten haben, alle Plätze in ihrer Gesamtheit durchnummeriert sind (also 1 - 25, nicht Reihe 1 Plätze 1-5, Reihe 3 Plätze 1 - 5).

Hier zur Verdeutlichung:
![corona-plan-c2](https://user-images.githubusercontent.com/8234890/126143228-a4d031e0-6a76-4b25-9e72-34e8271fc200.png)

Gebe ich nun im Generator ein "5 Reihen mit 5 Plätzen", dann wirft er mir auch für Reihe 2 5 Plätze (1-5) raus. Das birgt die Gefahr, dass die Teilnehmenden sich in Reihe 2 hinsetzen, weil das System das ja so vorgibt, und die Teilnehmenden nicht verstehen, dass Reihe 2 in Wirklichkeit die Reihe 3 im Hörsaal ist, weil die vor Ort vorhandene Reihe 2 nicht gebucht werden darf. Das bedeutet, ich müsste alle Plätze doch noch einmal händisch ändern. 

Gäbe es dafür eine Lösung, dass man z. B. sagt, man kann über den Generator auch einfach nur eine Menge X an Plätzen anlegen ohne Reihe? Oder eine andere praktikable Lösung?

**Comment by thenickless** [comment]
Hallo,

in diesem Fall würde ich auf die Bezeichnung der Reihen verzichten und nur 1 Reihe mit 25 Plätzen generieren lassen. 
Das Ergebnis wäre Platz A1 bis A25. 

Im Generator unter wp-admin/tools.php?page=rrze-rsvp-tools wären das diese Einstellungen:

![Bildschirmfoto 2021-08-04 um 13 23 43](https://user-images.githubusercontent.com/54806119/128172815-0c1a4edd-275d-4c4b-9552-39096ac7298f.png)

**Comment by cibsell** [comment]
Die Reihe wird dann trotzdem benannt, nämlich "A". Das müssen wir dann händisch alles rauslöschen. Das ist noch mühsamer, als wenn wir die Plätze händisch anlegen. Das hilft leider auch nicht weiter.

**Comment by thenickless** [comment]
Eine Alternative wäre 25 Reihen und 1 Platz pro Reihe mit Reihennummerierung "Numerisch" und Platz "A-Z", falls Plätze 1A bis 25A akzeptabel sind. Ist es in der Praxis tatsächlich ein Problem, wenn ein Zusatz dabei ist, der nicht weiter verwendet wird? "1A" oder "A1" anstelle von "1"

Ich schau mal kurz, ob der Generator mit vertretbarem Aufwand so umgebaut werden kann, dass weder bei Reihenanzahl == 1 noch bei Platzanzahl == 1 die Reihe bzw der Platz mit in der Bezeichnung aufgenommen wird und es dann Plätze mit der Bezeichnung "1" bis "25" ausgegeben werden. Die Bezeichnung hat keinen weiteren Einfluss im Code und wird nicht in einem Reihe/Plätze-Grid ausgeben.

**Comment by thenickless** [comment]
Umgesetzt - geht heute live mit Version 2.6.15:

Wenn es nur 1 Reihe gibt, dann werden die Plätze ohne Pre- und Suffix generiert:

Einstellungen dazu
- Reihen: 1
- Reihen: numerisch
- Plätze: 25
- Plätze: numerisch

geniert Plätze "1" bis "25"

**Comment by cibsell** [comment]
Danke!

**Comment by thenickless** [comment]
Gerne! Ist Live
