### ISSUE TITLE
3G Regelung einfügen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#294]
Folgender Text soll bei der Buchung von Plätzen hinzugefügt werden.

Dieser Text wird dem vorhandenen DSGVO-Text (Array-Key 'dsgvo-declaration', config.php) der mit einer obligatorischen Checkbox verbunden ist, hinzugefügt.
(Alternativ: Zusätzliche obligatorische Checkbox mit diesem Text. Macht aber von der Usability keinen Sinn.).

```
<h4>Ergänzende Auflagen zur 3G-Regelung</h4>
<p>
Ich bestätige mit dieser freiwilligen Selbstauskunft die jeweils aktuell gültigen Auflagen zur 3G-Regelung zum Besuch der Einrichtung zu erfüllen und kann dies nachweisen:
</p>
<ul>
 <li>Vollständig gegen COVID-19 geimpft und im Besitz eines Impfnachweises im Sinne der <abbr title="COVID-19-Schutzmaßnahmen-Ausnahmenverordnung ">SchAusnahmV</abbr>.</li>
<li>Genesen und im Besitz eines Genesenennachweises im Sinne der <abbr title="COVID-19-Schutzmaßnahmen-Ausnahmenverordnung ">SchAusnahmV</abbr>.</li>
<li> Getestet und im Besitz eines negativen Testnachweises (schriftlich/ elektronisch), der von der <abbr title="Bayerische Infektionsschutzmaßnahmenverordnung">BayIfSMV</abbr> als Nachweismöglichkeit aufgeführt wird (vgl. <a href="https://www.stmgp.bayern.de/coronavirus/rechtsgrundlagen/">https://www.stmgp.bayern.de/coronavirus/rechtsgrundlagen/</a>)</li>
 </ul>
<p>
<strong>Hinweis:</strong> Wenn Sie vorsätzlich oder fahrlässig gegen die 3G-Regel der jeweils geltenden BayIfSMV verstoßen, handeln Sie ordnungswidrig und es kann gegen Sie ein Bußgeldverfahren eingeleitet werden.
</p>
 
```

**Comment by rvdforst** [comment]
Done! Vgl. 957f2870c10682b2b26fe3b68e187f72339084e2

**Comment by xwolfde** [comment]
Sorry, muss neu öffnen: Ich bekam gerade jetzt ne Mail mit der englischen Übersetzung:

Bitte auch die englischen Variante ergänzen:


<h4>Additional Requirements regarding Covid-19</h4>
<p>
I hereby confirm with this voluntary disclosure that I comply with the currently valid requirements regarding Covid-19 vaccination, testing or recovery (‘3G-Regelung’) to enter this institution and can prove this fact with one of the following:
</p>
<ul>
 <li>I am fully vaccinated against Covid-19 and am in possession of proof of vaccination as defined by the Covid-19 Protective Measures Exemption Directive  <abbr title="COVID-19-Schutzmaßnahmen-Ausnahmenverordnung ">SchAusnahmV</abbr>.</li>
<li>I have recovered from an infection with Covid-19 and am in possession of proof of recovery as defined by the Covid-19 Protective Measures Exemption Directive <abbr title="COVID-19-Schutzmaßnahmen-Ausnahmenverordnung ">SchAusnahmV</abbr>.</li>
<li> I have been tested and am in possession of proof of a negative test result (on paper/electronic) listed as a valid type of proof in the Bavarian Regulation on Infection Prevention and Control Measures  (please refer to  <a href="https://www.stmgp.bayern.de/coronavirus/rechtsgrundlagen/">https://www.stmgp.bayern.de/coronavirus/rechtsgrundlagen/</a>)</li>
 </ul>
<p>
<strong>Please note:</strong> You are committing an offence and could be liable for a fine if you wilfully or negligently fail to comply with the rules requiring proof of Covid-19 vaccination, testing or recovery (3G-Regelung) as set out in the current version of the Regulation on Infection Prevention and Control Measures (BayIfSMV).
</p>

**Comment by rvdforst** [comment]
Done! Vgl. db12a460073c054cf82f7d8ad2eb704ce326cb51
