### ISSUE TITLE
Überschrift für Regularien fehlerhaft (WCAG-Fehler)

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#307]
Bei den regularien wird eine h4 Überschrift verwendet.

Da vorher keine h3 und davor keine h2 existiert ist dies falsch.
![grafik](https://user-images.githubusercontent.com/1070669/148820385-dd38aefe-411c-4588-93cf-60fe2e8637a5.png)

Bitte ggf. die h4 in ein <strong> ändern oder für eine richtige Überschriftenhierarchie sorgen.

**Comment by cassandre** [comment]
Das kann man in den Einstellungen selbst festlegen:
![Bildschirmfoto 2022-01-11 um 09 52 35](https://user-images.githubusercontent.com/4435815/148911048-ab9393ef-94b4-4a05-adf9-eb7bdcb87496.png)

**Comment by thenickless** [comment]
2.7.8 : Vorgabe von <h4> auf <strong> geändert
