### ISSUE TITLE
Automatische Sitzplatzerstellung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#33]
In Räumen mit einer größeren Anzahl an SItzplätzen ist es nicht handhabbar, wenn jeder Sitzplatz einzelnt angelegt werden muss. Bei Hörsälen mit mehreren Hundert Plätzen wäre dies ein NoGo.

Daher sollte ein Automatismus angeboten werden mit dem man Plätze eines Raumes automatisch anlegen lassen kann.

Eingaben: 
* Anzahl der Reihen
* Anzahl der Plätze pro Reihe
* Typ Nummerierung der Reihen (A-Z oder Numerisch)
* Typ der Nummerierung innerhalb der Reihe  (Numerisch oder A-Z)
* Taxonomie der Ausstattung mit der die Sitzplätze angelegt werden (kann man später dann wieder ändern)
* Pointer zum Raum

**Comment by cassandre** [comment]
In 42fe987f8a34db95fa0ff33ae76901bf386ad648 drin.
