### ISSUE TITLE
Klickbereiche bei Sitzplätzen mit einer Nummer etwas gering

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#39]
Es ist etwas schwer, mit der Maus die richtige Nummer zu treffen
![grafik](https://user-images.githubusercontent.com/1070669/89524563-51955080-d7d4-11ea-990e-2b42e7653040.png)

Wäre es sinnvoll, die Plätze anders zu formatieren? 
Zum Beispiel das Format, welches wir auch bei Paginations verwenden (also um jede Zahl einen eckigen Border drumherum mit der CI-Farbe). Dann ein Margin bis zum nächsten Platz und ein entsprechenden hover/focus.

**Comment by cassandre** [comment]
In 215e040eef79483bd49af81f13b0e9062e27c5c6 erledigt.
