### ISSUE TITLE
Index für den CPT fehlt /room/

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#41]
vgl: 
https://www.wordpress.rrze.fau.de/room

=> 404

**Comment by rvdforst** [comment]
Man muss die Funktion flush_rewrite_rules() ausführen oder im Dashboard > Einstellungen > Permalink auf "Änderungen speichern" klicken.

**Comment by xwolfde** [comment]
nee, das hatte ich gemacht.
und einen Raum unter /rooms/ kann ich aufrufen. Nur eben den Index nicht.

**Comment by rvdforst** [comment]
ist erledigt.
