### ISSUE TITLE
Fehlerhafte Bis-Zeit bei Buchungsbestätigung im Web

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#45]
Bei der Anzeige des Timeslots einer Buchung wird die falsche Bis-Zeit angezeigt (nämlich nochmal den Beginn):
![grafik](https://user-images.githubusercontent.com/1070669/89542014-a0e87a80-d7ee-11ea-8b34-9581abe63618.png)

**Comment by cassandre** [comment]
Ich vermute, das hängt mit diesem Issue zusammen: https://github.com/RRZE-Webteam/rrze-rsvp/issues/50#issuecomment-670455093, da es sich um denselben Timeslot handelt: Da das Ende des Timeslots nicht im Raum gespeichert war, wurde es bei der Buchung nicht ausgegeben. Fallback ist in dem Fall die Startzeit.
