### ISSUE TITLE
Buchung über SSO: Keine Daten im Formular nutzen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#46]
Wenn eine Buchung über SSO erfolgt, werden Vorname, Nachname und E-Mail **nicht** über das Formular gesendet und verwendet. 
Stattdessen werden diese Daten nach Abschicken des Forms aus dem SSO geholt.

Im Falle von Login über SSO braucht man die drei Datensätze auch nicht bei dem Buchungsformular anzeigen. Stattdessen reicht ein Hinweis darauf, dass für die E-Mail der Eintrag aus dem IdM verwendet wird.

Hintergrund: Auch wenn SSO an ist, kann man sonst das Formular modifizieren und jemand anders anmelden.

**Comment by cassandre** [comment]
fixed in 7e6e3ac7ca6cde593857f853a82e7111ebf6c7de
