### ISSUE TITLE
Mailtemplate für zu bestätigende Buchungen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#49]
Aktuell noch mit irreführenden Text, der auch im deutschen Part nicht deutsch ist:

In diesem Fall müsste die Buchung erst noch durch den User durch Klick auf Confirm bestätigt werden. 

Statt "Ihre Buchung wurde bestätigt."  müsste da also eher stehen:
"Bitte bestätigen Sie ihre Reservierung"

und statt
"Wir freuen uns Ihnen mitteilen zu können, dass Ihre Buchung bestätigt werden konnte."

müsste da stehen:

"Um die Buchung für den gewählten Sitzplatz zu bestätigen, klicken Sie bitte den folgenden Button:
       Buchung jetzt bestätigen.

Bitte beachten Sie, dass nicht bestätigte Buchungen nach einer Stunde automatisch verfallen.

```

(English version below)
Ihre Buchung wurde bestätigt.

Wir freuen uns Ihnen mitteilen zu können, dass Ihre Buchung bestätigt werden konnte.

10. August 2020 10:00 - 10:30

CIP-Pool
Hinten

Please confirm your booking.

Please check-in your booking on site.

Please check out when you leave the site.

Add the booking to your calendar.

```

**Comment by rvdforst** [comment]
Ist erledigt.
