### ISSUE TITLE
Fehler bei der Anzeige von Timeslots

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#50]
Bei der Buchungsseite werden vergangene Timeslots (des selben Tages) gezeigt. 
Der Screenshot ist von 12:00 Uhr:

![grafik](https://user-images.githubusercontent.com/1070669/89634463-f7a88f80-d894-11ea-84d8-6aa521226adf.png)

Außerdem wird der erste Timeslot falsch dargestellt (fehlende Endzeit).

**Comment by xwolfde** [comment]
Auch in der Übersicht der Verfügbarkeiten:
![grafik](https://user-images.githubusercontent.com/1070669/89636168-b796dc00-d897-11ea-9b24-a56111514a2b.png)

**Comment by cassandre** [comment]
Da hat vielleicht irgendwas mit dem Speichern von CMB nicht geklappt. Habe den Raum einmal geöffnet, ohne Änderungen gespeichert, jetzt wird die End-Zeit normal angezeigt.

**Comment by xwolfde** [comment]
Problem noch immer vorhanden.

**Comment by xwolfde** [comment]
fixed
