### ISSUE TITLE
Validation Telefonnummer

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#52]
Neben der Prüfung ob es sich bei der Eingabe um Nummern handelt, auch prüfen, ob die Mindestlänge erfüllt ist.

**Comment by thenickless** [comment]
done. https://github.com/RRZE-Webteam/rrze-rsvp/commit/c121a6fba27635d265d596e3b3c2551a4fc1b0a5

- HTML5 pattern="^[0-9-+\s()]*$"
- validatePhone() => prüft derzeit nur auf >=10 Ziffern, erlaubt sind Ziffern und + ( ) / -
