### ISSUE TITLE
Ermöglichen der Eingabe eines Kommentarfeldes für Bucher

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#57]
Bucher sollen Optional ein Kommentarfeld (Freitext/Zeile, aber nicht zu lang) bekommen, wenn dies bei dem Raum so als Option angegeben ist.

Hierin kann der Bucher bespndere Hinweise geben, z,b. das er Hilfe braucht oder sonsige Angaben machen.

nd ja, es kann auch für den Anbieter des Raumes genutzt weren um spezielle Angaben zu erfragen. Dies betrifft dann insbesondere Buchungen von Sprechstunden.

**Comment by cassandre** [comment]
Ein Kommentar-Feld ist im CPT Booking eh schon vorhanden, war eher intern gemeint.  Da kann man natürlich wunderbar dafür hernehmen und bei Bedarf in das Formular integrieren.
