### ISSUE TITLE
PDF Erstellen als Option bei der Raumübersicht im Backend

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#61]
Um das PDF zu erstellen, muss man aktuell so vorgehen:

- Auf die Raumbearbeitung gehen: .../wp-admin/edit.php?post_type=room
- Den Raum auswählen, zu dem man die Blätter erstellen will (derzeit nur der eine)
- Oben bei der Auswahl Mehrfachaktionen auf "PDF erstellen" wechseln
- Übernehmen klicken.
- Dann erscheint oben ein Button mit
	"x PDFs wurden erstellt". 
- Darauf klicken, dann erhält man die PDF.
	

![grafik](https://user-images.githubusercontent.com/1070669/89778064-63406600-dafc-11ea-9eb6-e310d3d1cddb.png)

Schöner wäre es, wenn man, wo man in der Regel eh nur einen Raum auswählen will, die Option "PDF erstellen" in der Liste der Aktionen pro Raum angezeigt bekommt, die man sieht, wenn man über ein Raum rüberhovert.

**Comment by cassandre** [comment]
Könnte man zusammen mit der Sitz-Generierung (TODO) in die Werkzeuge packen. Da passt es semantisch am ehesten hin (hatten Rolf und ich beim Sitz-Generator neulich beschlossen).

**Comment by thenickless** [comment]
PDF kann nun sowohl über die Mehrfachaktionen als auch in der Liste der Aktionen von "Räumen" und "Sitzplätzen" erstellt werden.
