### ISSUE TITLE
Buchungsformular ergänzen um verbindliches Feld zur Freigabe der Kontaktdaten

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#62]
Bei der Buchung ist ein verbindliches Feld (Checkbox) einzufügen, mit der Bucher bestätigen, dass die Kontaktdaten 

"Für die Dauer des Vorganges der Platzbuchung und bis zu 4 Wochen danach zum Zwecke der Nachverfolgung gemäß der gesetzlichen Grundlagen zur Corona-Bekämpfung gespeichert werden dürfen. Ebenso wird Raumverantwortlichen und Veranstalter von Sprechstunden das Recht eingeräumt, während der Dauer des Buchungsprozesses und bis zum Ende des ausgewählten Termins Einblick in folgende Buchungsdaten zu nehmen: E-Mailadresse, Name, Vorname.  Raumverantwortliche und Veranstalter von Sprechstunden erhalten diese Daten allein zum Zweck der Durchführung und Verwaltung des Termins gemäß §6 Abs1 a DSGVO."

**Comment by cassandre** [comment]
Es fehlt noch ein Hinweis, wofür die Telefonnummer erfasst und von wem sie eingesehen werden darf.

**Comment by xwolfde** [comment]
Dann füg einfach den Satz hinzu, dass "Die Telefonnummer wird nur zum Zwecke der Kontaktverfolgung aufgrund der gesetzlicher Grundlagen zur Pandemiebekämpfung für Gesundheitsbehörden erfasst".

**Comment by xwolfde** [comment]
Ich glaub der Issue kann geschlossen werden, oder?
