### ISSUE TITLE
Defaults in Settings

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#69]
Hier scheinen keine Defaults gesetzt zu sein, nachdem man das Plugin aktivierte.
Die Aktivierung des Plugins sollte ein paar typische Defaults setzen, die am sinnvollsten sind für dei Allgemeinheit:
![grafik](https://user-images.githubusercontent.com/1070669/89882853-eb834180-dbb6-11ea-8e20-5d1056c6102f.png)

**Comment by xwolfde** [comment]
Auch hier bitte Defaults rein. Mailadresse als Default sollte bei der Erstinstallation die Mailadresse der CMS Instanz sein.


![grafik](https://user-images.githubusercontent.com/1070669/89883093-3bfa9f00-dbb7-11ea-8750-8bbcc45c8242.png)

**Comment by thenickless** [comment]
Feld für die Buchungsseite fällt weg

**Comment by thenickless** [comment]
+ Usability verbessern:

Bei Auswahl Felder "ausgrauen", die sich gegenseitig ausschließen

**Comment by thenickless** [comment]
done.  https://github.com/RRZE-Webteam/rrze-rsvp/commit/db20484d73739dbc8dec8d061211069b8fe6821c

Defaults waren bereits angelegt, lediglich im falschen Format (zB 1 anstelle von 'yes').
