### ISSUE TITLE
Buchungsmail: Titel

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#70]
"Sie erhielten eine neue Reservierungsanfrage für Die WordPress-Themes für Fakultäten, Lehrstühle und Einrichtungen."

Ich würde da den Titel der Website weglassen oder es umstellen:

Links das Logo/Titel der Website.
Dann die Trennlinie.
Und dann den Text:
"Sie erhielten eine neue Reservierungsanfrage:"

![grafik](https://user-images.githubusercontent.com/1070669/89891559-d3b2ba00-dbc4-11ea-9106-21aba85f0ef2.png)

**Comment by xwolfde** [comment]
Ich erhielt die Mail übrigens 2mal?

**Comment by xwolfde** [comment]
Außerdem bitte die Telefonnnummer rausnehmen.

**Comment by xwolfde** [comment]
Ggf. auch das Look&Feel der Bestätigungsmail anpassen. Die sieht ja im Vergleich zu obiger Mail nicht so schön aus:


![grafik](https://user-images.githubusercontent.com/1070669/89898838-ecc16800-dbd0-11ea-8959-64ac698703d4.png)

**Comment by rvdforst** [comment]
> Ich erhielt die Mail übrigens 2mal?

Es wurde behoben. Vgl. dc88880f1b1d7c323ceb4bca4f8304f61e63f343

**Comment by rvdforst** [comment]
Ist erledigt. Alle Templates wurden neu gestaltet.
