### ISSUE TITLE
Feedback zur Buchungsseite

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#73]
Feedback aus der Informatik: Besser statt den roten Warnhinweis-Alert (unten) den gelben Hinweis -Alert nehmen.

![grafik](https://user-images.githubusercontent.com/1070669/89907371-1d5acf00-dbdc-11ea-97bc-82377bff5a98.png)

**Comment by cassandre** [comment]
Hatte ich nicht gesehen und ihn jetzt blau gemacht – ist ja eine Info.
Darunter – falls entsprechend im Raum eingestellt – der Hinweis, an den Check-In zu denken in gelb.
Rot wird nur der Hinweis, die Buchung zu bestätigen, denn da ist ja eine unmittelbare Aktion erforderlich. Das steht dann auch direkt oben, nicht unten.
vgl. da144877aa154117c538fb5f3b6745add028fca2
