### ISSUE TITLE
Mailtemplate Buchungsbestätigung: Zeitangaben?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#74]
Bei der Mail zur Bestätigung einer Buchung ist im deutschen Teil kein "Uhr" angegeben. Bei der englischen Angabe wird "pm" ergänzt.
![grafik](https://user-images.githubusercontent.com/1070669/89910591-f43c3d80-dbdf-11ea-898a-264f8f15fff3.png)

(Ja, ich weiß dass es nicht dasselbe ist).

**Frage**: Sollten wir da um der gewohnten Schreibweise im Deutschen gerecht zu werden bei der Zeitangabe ein "Uhr" dahinter setzen?

**Comment by rvdforst** [comment]
Unbedingt!

**Comment by rvdforst** [comment]
Das Zeitformat hängt von der Einstellungen in WP ab (Vgl. Einstellungen / Allgemein / Zeitformat). Wenn wir also das Suffix "Uhr" hinzufügen möchten, sollte das Zeitformat wie folgt sein: G:i \U\h\r
