### ISSUE TITLE
Anzeige Raumbelegung..?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#79]
Hier scheint mir mehreres seltsam:
![grafik](https://user-images.githubusercontent.com/1070669/90266672-dd962080-de43-11ea-8a9b-9b6d82165862.png)

- Die Sortierung der Plätze ist komisch.
- Der Raum hat weitere Timeslots, die werden nicht gezeigt. Ggf. wäre es sinnvoll anzugeben, wann der nächste Zeitslot sein wird.
- Warum zeigt er mir jetzt um 17:30 die Raumbelegung für 9.12 Uhr? (In dem EIntrag hab ich für heute keine weitere Slots mehr gehabt. Eigentlich müsste daher jetzt da stehen: Derzeit stehen keine Slots zur freien Verfügung. Der nächste Zeitpunkt an dem der Raum veffügbar ist, ist Datum. Zeit von - Zeit bis."
- Bei der Tableheadline fehlt links ein "Platz" als Titel
- Die headline rechts hat genügend Platz um Start und Endzeit nebeneinander zu zeigen, trotzdem ist hier ein Umbruch. Warum? Das `<br>` wegmachen und den Browser den Umbruch überlassen..

**Comment by xwolfde** [comment]
Ggf. aus der Adminsicht einen Link auf die Öffentliche Seite der Raumbelegung anbieten. Plus zusätzlich den Link für den Aufruf in der Embedded form.
Einfach oben als Links angeben:

`"Links zur öffentlichen Anzeige der aktuellen Raumbelegung:  <a href="">Normale Website</a>, <a href="">Website für Public Displays</a>"`

**Comment by thenickless** [comment]
`<span class="rrze-rsvp-start bzw ...-end"> um die Zeiten `

**Comment by thenickless** [comment]
umgesetzt:

- Die Sortierung der Plätze ist komisch.
- Bei der Tableheadline fehlt links ein "Platz" als Titel.
- Die headline rechts hat genügend Platz um Start und Endzeit nebeneinander zu zeigen, trotzdem ist hier ein Umbruch. Warum? Das <br> wegmachen und den Browser den Umbruch überlassen..
- <span class="rrze-rsvp-start bzw ...-end"> um die Zeiten => <span class="rrze-rsvp-timespan">

**Comment by thenickless** [comment]
- Warum zeigt er mir jetzt um 17:30 die Raumbelegung für 9.12 Uhr? (In dem EIntrag hab ich für heute keine weitere Slots mehr gehabt. Eigentlich müsste daher jetzt da stehen: Derzeit stehen keine Slots zur freien Verfügung. Der nächste Zeitpunkt an dem der Raum veffügbar ist, ist Datum. Zeit von - Zeit bis."

Die Raumbelegung zeigt die Belegung des ausgewählten Raums für heute.

Ich habe daher die irreführende Beschrifttung von "Current room occupancy" zu "Room occupancy for today" geändert.

**Comment by thenickless** [comment]
done. https://github.com/RRZE-Webteam/rrze-rsvp/commit/4dc04741a05f93245c980898f17a0c29462693e4
