### ISSUE TITLE
Zentraler Abruf für Kontaktverfolgung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#89]
Für den Fall, dass es zu einer Anfrage des Gesundheitsamtes kommt, ist die Bereitstellung einer Exportfunktion für Kontaktdaten notwendig.
Hierbei soll bei Eingabe von Identifikationsmerkmalen für eine Person (Name, E-Mail und oder Telefon) und einem Zeitpunkt und einem Zeitdelta (x Tage vor dem Zeitpunkt, y Tage nach dem Zeitpunkt) eine Liste aller weiteren Kontakte ausgegeben werden, die in diesem Zeitraum im selben Raum  waren wie die gesuchte Person.

Diese Suchfunktion soll  zentral über alle Instanzen einer WordPress-Installation laufen können und nur von einer extra hierfür eingerichteten Rolle oder den Superadmins aufgerufen werden können. 
Die Funktion soll nicht von einfachen Raumverantwortlichen einer Installation aufrufbar sein.

Als Exportformat sollte ein CSV-Format reichen, welches folgende Felder enthält:
Name, Vorname, E-Mail, Telefon, Zeitpunkt des Kontakt/Nähe mit gesuchter Person, Raumangabe, Raumadresse

**Comment by rvdforst** [comment]
Die Tracking-Daten werden nicht in der wp_sitemeta-WP-Tabelle gespeichert. Der Grund dafür ist, dass in einem Array gespeicherte serialisierte Daten Probleme verursachen können, wenn die Datenmenge groß ist. Stattdessen werden die Daten mittels der Tracking-Klasse (Tracking.php) in einer "custom" DB-Tabelle (wp_rrze_rsvp_tracking) gespeichert. Die entsprechenden Daten werden mit dem Action-Hook "rrze-rsvp-ckecked-in" erfasst (vgl. Actions::bookingReplyCustomer() u. Tracking::onLoaded()).

Tracking-Daten, die älter als 4 Wochen sind, werden automatisch gelöscht. Vgl. Schedule::deleteOldTrackingData()

**Comment by thenickless** [comment]
Umgesetzt in https://github.com/RRZE-Webteam/rrze-rsvp/commit/e48783e48cfeb1ae5f32fb7e512394cb0f5ccffe#diff-bb2b21ef7774df8687ff02b0284505c6 und https://github.com/RRZE-Webteam/rrze-rsvp-network/commit/fce28fa8362ba643455a408efb5082824014ffb3

**Comment by thenickless** [comment]
Der Übersicht halber schließe ich das Issue - Grundfunktionalität ist umgesetzt - noch offene Punkte sind hier:

- https://github.com/RRZE-Webteam/rrze-rsvp/issues/110
- https://github.com/RRZE-Webteam/rrze-rsvp/issues/111
- https://github.com/RRZE-Webteam/rrze-rsvp/issues/112
