### ISSUE TITLE
Excerpt beim CPT Room

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#93]
Brauchen wir das Eingabefeld für den Excerpt? Wenn nein, sollten wir es wegnehmen.

**Comment by cassandre** [comment]
Könnte man in einer noch zu erstellenden archive-room.php nutzen. Im Moment wird in /room/ ansonsten der komplette Content angezeigt.

**Comment by xwolfde** [comment]
Hm, die index gibt es doch schon?
http://test8.tindu.rrze.uni-erlangen.de/room/

**Comment by cassandre** [comment]
Jain. Index funktioniert, nimmt aber die Standard-Index, da bislang keine für diesen CPT definiert.

**Comment by xwolfde** [comment]
Sehe ich jetzt weniger schlimm an, als Supporttickets von Leuten, die wegen dem Eingabefeld irritiert sind...
Wenn wir das wieder brauchen, können wir es ja wieder einfügen.

**Comment by cassandre** [comment]
OK, wird gekillt.
