### ISSUE TITLE
Darstellung SSO-Login

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#94]
Kann man die Seite mit dem SSO-Login optisch anders machen? ggf. als Content-Teil des Themes?

Außerdem gibt es die Frage, warum da zwei Links sind, die eigentlich dasselbe Ziel haben?

![grafik](https://user-images.githubusercontent.com/1070669/90654537-03e70200-e230-11ea-84d7-f5a08ff1e36e.png)

**Comment by rvdforst** [comment]
Ist erledigt (V. 0.3.8-0)
