### ISSUE TITLE
Räume an einzelnen Tagen blockieren (Feiertage etc.)

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-rsvp#96]
Die eingestellten Termine gelten für alle jeweiligen Wochentage. Es muss aber die Möglichkeit geben, an Feiertagen, Betriebsferien etc. Ausnahmen einzupflegen. 
Vorschlag: Einfach eine Liste (Textarea) mit einem Datum pro Zeile (Vorteil: schnell zu bearbeiten, copy&paste möglich, übersichtlich; Nachteil: muss heftigst validiert werden)
Alternative: Wiederholbare Felder mit CMB2 (Vorteil: Eingabe ist standardisiert, Nachteil: Aufwändiger einzutragen, braucht ziemlich viel Platz im Backend, braucht wahrscheinlich zusätzlich eine Import-Lösung)
Offen für weitere Lösungen...

**Comment by xwolfde** [comment]
Gute Idee , Quick und Dirty eine Textarea in den Settings, die wir mit eine Liste an bay. Tagen vorfüllen?

**Comment by cassandre** [comment]
> Gute Idee , Quick und Dirty eine Textarea in den Settings, die wir mit eine Liste an bay. Tagen vorfüllen?

Bist du sicher dass alle Räume an Feiertagen geschlossen sind?

Und sollten die Einstellungen für alle Räume gelten (-> Settings) oder können sie für unterschiedliche Räume verschieden sein (Bereichsbibliothek hat zu, aber die UB ist geöffnet -> Edit-Room)?

**Comment by cassandre** [comment]
fixed in 0d9f96a
