### ISSUE TITLE
Fehlermeldung bei einer Buchung: Telefonnummer?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-rsvp#99]
Rückmeldung von Tester:

> Wenn man bei der Buchung eine Telefonnummer ohne Vorwahl angibt, erhält man im
> Moment nach abschicken der Buchung eine Fehlermeldung „Ungültige oder fehlende
> Buchungsdaten.“ Kann man diese Meldung noch präzisieren?

**Comment by rvdforst** [comment]
Hier müssen wir die Validierung aller Felder des Formulars neu überarbeiten. Wie es jetzt ist, ist es nicht benutzerfreundlich.

**Comment by xwolfde** [comment]
Telefonnummer kann bei internen Nummern auch kleiner als 10 Nummern sein, aber mindestens 3.

**Comment by xwolfde** [comment]
#52

**Comment by xwolfde** [comment]
fixed
